spring:
  profiles:
    active: docker
  application:
    name: wiki-ingest-service
  cloud:
    stream:
      bindings:
        output:
          binder: kafka
          destination: ${WIKIMEDIA_TOPIC}
          contentType: 'application/json'
          group: ${PRODUCER_GROUP}
          producer:
            requiredGroups: ${PRODUCER_GROUP}
            compressionType: ${COMPRESSION_TYPE:none}
server:
  port: ${PORT:${SERVER_PORT:8100}}
---
spring:
  profiles: development
  cloud:
    stream:
      kafka:
        binder:
          brokers: "PLAINTEXT://localhost:29092"
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS} #"PLAINTEXT://kafka-0:29092"
---
spring:
  profiles: kubernetes
  cloud:
    stream:
      kafka:
        binder:
          brokers: "PLAINTEXT://kafka:9092"
---
spring:
  profiles: test
